FROM mcr.microsoft.com/playwright:v1.10.0-focal

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV RELEASE_MODE=1

# Playwright 浏览器下载加速
ENV PLAYWRIGHT_DOWNLOAD_HOST=https://npmmirror.com/mirrors/playwright

RUN mkdir -p /app/log
ENV app=/app
ADD . ${app}
WORKDIR ${app}

RUN pip install --upgrade pip -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
RUN pip install -r requirements.txt -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
RUN python3 -m playwright install
RUN playwright install-deps
CMD ["python3", "main.py"]