FROM mcr.microsoft.com/playwright:v1.40.0-focal

ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Playwright 浏览器下载加速
ENV PLAYWRIGHT_DOWNLOAD_HOST=https://npmmirror.com/mirrors/playwright


# 安装pip
RUN apt-get update && apt-get install -y python3-pip

ENV RELEASE_MODE=1
RUN mkdir -p /app/log
ENV app=/app
ADD . ${app}
WORKDIR ${app}

RUN pip3 install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple/ --trusted-host pypi.tuna.tsinghua.edu.cn
RUN pip3 install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple/ --trusted-host pypi.tuna.tsinghua.edu.cn
RUN python3 -m playwright install
# 启动命令
CMD ["python3", "main.py"]