export TASK_TYPE=spider_jinzheng_pages2mgo
export SPIDER_HEADLESS=True
export SPIDER_BROWSER=chromium
export SPIDER_PAGE_KEY=all
export CACHE_REDIS_HOST=153.35.13.226
export CACHE_REDIS_PORT=6379
export CACHE_REDIS_PASSWORD=5S4Zt7wCCktYJnpAQPHZ
export MONGO_HOST=153.35.13.226
export MONGO_PORT=27017
export MONGO_DB=aquabridge
export MONGO_PASSWORD=Aquabridge#2025
export MONGO_USER=aquabridge
export SELECTED_DIRECTORY=aquabridge
export RUN_ONCE=1
export SCHEDULER_FLAG=1
export INTERVAL_START_TIME="2025-10-15 00:00:00"
export SCHEDULER_MODE=interval
export INTERVAL_HOUR=3